### ISSUE TITLE
Runtime error introduced via one of the latest changes?

### ISSUE THREAD

**Issue by arindamsaha1507** [djgroen/facs#26]
Hi Derek,

I have been getting this bug while running the code via FabSim:

RuntimeError:
local() encountered an error (return code 2)while executing 'ssh -Y -p 22 arindam@localhost '/bin/true || true && /home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/localhost_exe/FabSim/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475/klaipeda_localhost_1_extend-lockdown-1-0.475.sh''

The exact command I ran was

fabsim localhost covid19_ensemble:cheshire_east,TS='extend-lockdown',TM='1',cores=1,replicas=1,ci_multipliers=0.3,simulation_period=100

I see this bug since the update to the code about 4 days ago.

**Comment by djgroen** [comment]
Hi Arindam.
Your syntax is actually wrong here. You should use:

`flh covid19_ensemble:configs='cheshire_east',TS='uk-forecast',TM='0',cores=1,replicas=1,simulation_period=100,starting_infections=460,job_wall_time=1:00:00,solver=pfacs`

You can freely change the other parameters of course, but the first one has to be `configs`. This is not correct in the current documentation, so I will update this now.

**Comment by djgroen** [comment]
The documentation is now updated. Arindam, would you be able to test this?

**Comment by arindamsaha1507** [comment]
> The documentation is now updated. Arindam, would you be able to test this?
 
The error still persists.

> 
> Note that I should probably update the TS/TM functionalities such that it triggers different measures.yml files. Perhaps I should rename names like 'uk-forecast' to actual names of measurement yml files?

Yes and yes! That would be very very useful.

**Comment by djgroen** [comment]
Hi Arindam.

Can you please paste in the full output of your command here in the thread, rather than just the tail? Then I will be able to better diagnose the underlying issue.

**Comment by arindamsaha1507** [comment]
Hi Derek,

The error with the last part of the output is as follows:

Transport: t 98 p_inf 6.0767680283333435e-06, inf_ext_pas 192321.5, # of infections 5.
98 8/6/2020 1.0 1.0
[382505      9     12   2117     35      0      5      0      0]
total visits: 553873
0 1282.5
[382505      6     14   2118     35      0      0      0      0]
Transport: t 99 p_inf 6.0768312182407525e-06, inf_ext_pas 192321.5, # of infections 2.
99 9/6/2020 1.0 1.0
[382503      8     14   2118     35      0      2      0      0]
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/localhost_exe/FabSim/results/cheshire_east_localhost_1/RUNS/extend-lockdown-1-0.475/cheshire_east_localhost_1_extend-lockdown-1-0.475.sh: 32: Syntax error: redirection unexpected
Traceback (most recent call last):
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/bin/fabsim", line 46, in <module>
    sys.exit(fabsim_main.main())
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/fabsim_main.py", line 150, in main
    env.exec_func(*env.task_args, **env.task_kwargs)
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/decorators.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/plugins/FabCovid19/FabCovid19.py", line 208, in covid19_ensemble
    run_ensemble(loc, sweep_dir, **args)
  File "<string>", line 91, in run_ensemble
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/fab.py", line 1112, in run_ensemble
    job_scripts_to_submit = job(
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/fab.py", line 667, in job
    job_submission(dict(job_script=job_script))
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/fab.py", line 918, in job_submission
    run(
  File "<string>", line 73, in run
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/networks.py", line 153, in run
    return manual(cmd, cd=cd, capture=capture)
  File "<string>", line 73, in manual
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/networks.py", line 221, in manual
    return local(pre_cmd + "'" + manual_command + "'", capture=capture)
  File "<string>", line 51, in local
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/networks.py", line 59, in local
    raise RuntimeError(
RuntimeError: 
local() encountered an error (return code 2)while executing 'ssh -Y -p 22 arindam@localhost '/bin/true || true &&  /home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/localhost_exe/FabSim/results/cheshire_east_localhost_1/RUNS/extend-lockdown-1-0.475/cheshire_east_localhost_1_extend-lockdown-1-0.475.sh''

**Comment by djgroen** [comment]
Ah, could you paste in the contents of the file cheshire_east_localhost_1_extend-lockdown-1-0.475.sh ?

There could be an error there.

**Comment by djgroen** [comment]
I am just checking my local run, and the script is as follows:

# no batch system



cd /home/csstddg/FabSim3/localhost_exe/FabSim/results/cheshire_east_localhost_4/RUNS/uk-forecast-0-0.475
/bin/true || true

# copy files from config folder
config_dir=/home/csstddg/FabSim3/localhost_exe/FabSim/config_files/cheshire_east
rsync -pthrvz --inplace --exclude SWEEP $config_dir/* .

# copy files from SWEEP folder
rsync -pthrvz --inplace $config_dir/SWEEP/uk-forecast-0-0.475/ .

if [ -z "/home/csstddg/facs" ]
then
        echo "Please set $facs_location in your deploy/machines_user.yml file."
else
        export PYTHONPATH=/home/csstddg/facs:$PYTHONPATH
fi

/usr/bin/env > env.log

current_dir=${PWD##*/}

start_time="$(date -u +%s.%N)"

mpirun -np 4 python3 /home/csstddg/facs/run.py --generic_outfile --location=cheshire_east  --transition_scenario=  --transition_mode=-1  --ci_multiplier=0.475  --output_dir=.  --data_dir=covid_data  --starting_infections=460  --start_date=1/3/2020  --simulation_period=500


end_time="$(date -u +%s.%N)"
elapsed="$(bc <<<"$end_time-$start_time")"
echo "Total Executing Time = $elapsed seconds"



... it seems like the error on your platform happens on the second to last line there.

**Comment by djgroen** [comment]
My recommendation would be to go into the results directory, and start this script manually using ./cheshire_east_localhost_1_extend-lockdown-1-0.475.sh

You'll then initially get the same error probably, but you can then try to fix the syntax on line 32 to figure out which setup will work. Once you have a syntax that works correctly while retaining the functionality, I can then test it on my platform.

If it then works on my platform as well, we can update the template for pfacs, and then fix the problem for good :).

**Comment by arindamsaha1507** [comment]
Just add 

```shell
#!/bin/bash
```

at the beginning of the script.

I commented out the python execution line to debug and it works there. I have now started running the script with the python execution. I will let you know if it succeeds.

**Comment by arindamsaha1507** [comment]
Adding the above-mentioned line to the shell script solves the problem for me. Can you update the template accordingly?

**Comment by djgroen** [comment]
Fixed for localhost using this change: 8ea375de62c1e47770934c45ae2d2d480177c146

No template change needed, I just changed a default config setting :).

Can you try to see if it works?

**Comment by arindamsaha1507** [comment]
Nicely done! :)
